-- 建表：targets
CREATE TABLE IF NOT EXISTS public.targets (
    id bigint generated by default as identity primary key,
    platform text,
    url text unique,
    name text,
    tags text default '',
    is_competitor smallint default 0
);

-- 建表：records
CREATE TABLE IF NOT EXISTS public.records (
    id bigint generated by default as identity primary key,
    target_id bigint references public.targets(id) on delete cascade,
    followers integer,
    scraped_at timestamp with time zone default timezone('utc'::text, now())
);

-- 建立索引以加速查詢
CREATE INDEX idx_targets_url ON public.targets(url);
CREATE INDEX idx_records_target_id ON public.records(target_id);
CREATE INDEX idx_records_scraped_at ON public.records(scraped_at);

-- 建表：competitor_posts
CREATE TABLE IF NOT EXISTS public.competitor_posts (
    id bigint generated by default as identity primary key,
    url text unique not null,
    content text,
    post_date text,
    brand text,
    platform text,
    likes integer default 0,
    comments integer default 0,
    shares integer default 0,
    engagement integer default 0,
    tags text[]
);
CREATE INDEX idx_competitor_posts_date ON public.competitor_posts(post_date);
